/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    QC_SUMMARY
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Generates QC metrics and reports for a PacBio HiFi variant calling run.

    Metrics collected:
        - alignment statistics   (samtools flagstat)
        - coverage metrics       (samtools coverage)
        - per-base depth         (samtools depth)
        - read metrics           (samtools stats)
        - variant statistics     (bcftools stats)

    Produces:
        - text QC report
        - coverage TSV
        - metrics JSON
        - HTML QC dashboard with coverage and variant position plots
          generated by scripts/report/generate_html_report.py

    Input:
        tuple (sample, bam, bai)  — aligned reads from ALIGN_MINIMAP2
        tuple (vcf, vcf_idx)      — final normalized variants from CALL_*
        tuple (reference, fai)    — indexed reference from INDEX_REFERENCE

    Output:
        tuple (sample, qc_txt, qc_html)

    Resource label:
        process_low — lightweight reporting step
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

process QC_SUMMARY {

    // -----------------------------------------------------------------------
    // tag / label
    // -----------------------------------------------------------------------
    tag "${sample}"
    label 'process_low'

    // -----------------------------------------------------------------------
    // conda
    // matplotlib installed via pip in environment.yml — available in the
    // conda environment without needing to declare it here.
    // -----------------------------------------------------------------------
    conda "bioconda::samtools=1.19 bioconda::bcftools=1.19 bioconda::seqkit=2.8.0"

    // -----------------------------------------------------------------------
    // container
    // Same main pipeline image as ALIGN_MINIMAP2 and CALL_BCFTOOLS.
    // matplotlib must be installed in the container for plots to render.
    // -----------------------------------------------------------------------
    container "${params.pipeline_container}"

    // -----------------------------------------------------------------------
    // publishDir
    // All report outputs published to outdir/reports/
    // Text report, HTML report, coverage TSV, and metrics JSON all kept
    // together for easy access.
    // -----------------------------------------------------------------------
    publishDir "${params.outdir}/reports", mode: 'copy'

    input:
    // -----------------------------------------------------------------------
    // BAM tuple — sample name bound here, reused for all output naming
    // -----------------------------------------------------------------------
    tuple val(sample), path(bam), path(bai)

    // -----------------------------------------------------------------------
    // VCF tuple — sample dropped here to avoid duplicate val(sample)
    // in the same input block. Sample is already bound from the BAM tuple.
    // Channel joining in the workflow ensures BAM and VCF are correctly
    // matched by sample before reaching this process.
    // -----------------------------------------------------------------------
    tuple path(vcf), path(vcf_index)  // sample already bound from BAM tuple

    // -----------------------------------------------------------------------
    // Reference tuple — fai staged automatically for bcftools
    // -----------------------------------------------------------------------
    tuple path(reference), path(fai)  // fai staged automatically

    output:
    // -----------------------------------------------------------------------
    // sample name travels with outputs for downstream traceability
    // -----------------------------------------------------------------------
    tuple val(sample), path("${sample}_qc_report.txt"), path("${sample}_qc_report.html")

    script:
    // -----------------------------------------------------------------------
    // projectDir
    // Nextflow built-in variable pointing to the root of the pipeline
    // repository. Used to locate scripts/report/generate_html_report.py
    // regardless of where Nextflow is run from.
    //
    // Intermediate files (coverage TSV, metrics JSON) are produced in
    // the work directory and used by generate_html_report.py but are
    // not declared as outputs — they stay in work/ only.
    // -----------------------------------------------------------------------
    """
    set -euo pipefail

    TXT_REPORT=${sample}_qc_report.txt
    HTML_REPORT=${sample}_qc_report.html
    COVERAGE_TSV=${sample}_coverage.tsv
    METRICS_JSON=${sample}_metrics.json

    # --------------------------------------------------
    # Text QC report
    # --------------------------------------------------

    echo "============================================"  > \$TXT_REPORT
    echo "PacBio HiFi Pipeline QC Report"              >> \$TXT_REPORT
    echo "Sample    : ${sample}"                        >> \$TXT_REPORT
    echo "Generated : \$(date '+%Y-%m-%d %H:%M:%S')"   >> \$TXT_REPORT
    echo "============================================" >> \$TXT_REPORT
    echo ""                                            >> \$TXT_REPORT

    echo "---- ALIGNMENT METRICS ----"                 >> \$TXT_REPORT
    samtools flagstat ${bam}                           >> \$TXT_REPORT
    echo ""                                            >> \$TXT_REPORT

    echo "---- COVERAGE METRICS ----"                  >> \$TXT_REPORT
    samtools coverage ${bam}                           >> \$TXT_REPORT
    echo ""                                            >> \$TXT_REPORT

    echo "---- READ METRICS ----"                      >> \$TXT_REPORT
    samtools stats ${bam} | grep "^SN"                 >> \$TXT_REPORT
    echo ""                                            >> \$TXT_REPORT

    echo "---- VARIANT SUMMARY ----"                   >> \$TXT_REPORT
    bcftools stats ${vcf} | grep "^SN"                 >> \$TXT_REPORT
    echo ""                                            >> \$TXT_REPORT

    echo "---- VARIANT PREVIEW (first 10) ----"        >> \$TXT_REPORT
    printf "%-10s %-10s %-6s %-6s %-8s %-10s\\n" \\
        "CHROM" "POS" "REF" "ALT" "QUAL" "FILTER"     >> \$TXT_REPORT
    bcftools view -H ${vcf} | head -10 | \\
        awk '{printf "%-10s %-10s %-6s %-6s %-8s %-10s\\n", \$1,\$2,\$4,\$5,\$6,\$7}' >> \$TXT_REPORT

    # --------------------------------------------------
    # Per-base coverage depth for plot
    # --------------------------------------------------

    samtools depth ${bam} > \$COVERAGE_TSV

    # --------------------------------------------------
    # Metrics JSON for HTML report
    # --------------------------------------------------

    MAPPING_RATE=\$(samtools flagstat ${bam} \\
        | grep "primary mapped" \\
        | grep -oE '[0-9]+\\.[0-9]+%' || echo "NA")

    VARIANT_COUNT=\$(bcftools view -H ${vcf} | wc -l | tr -d ' ')

    TITV=\$(bcftools stats ${vcf} \\
        | grep "^TSTV" \\
        | awk '{print \$5}' || echo "NA")

    echo "{" > \$METRICS_JSON
    echo "  \\"sample\\": \\"${sample}\\"," >> \$METRICS_JSON
    echo "  \\"mapping_rate\\": \\"\$MAPPING_RATE\\"," >> \$METRICS_JSON
    echo "  \\"variant_count\\": \$VARIANT_COUNT," >> \$METRICS_JSON
    echo "  \\"titv\\": \\"\$TITV\\"" >> \$METRICS_JSON
    echo "}" >> \$METRICS_JSON

    # --------------------------------------------------
    # HTML report — generated by validated Python script
    # projectDir points to the pipeline repository root
    # --------------------------------------------------

    python3 ${projectDir}/scripts/report/generate_html_report.py \\
        --sample   ${sample} \\
        --metrics  \$METRICS_JSON \\
        --qc       \$TXT_REPORT \\
        --coverage \$COVERAGE_TSV \\
        --vcf      ${vcf} \\
        --output   \$HTML_REPORT
    """

    // -----------------------------------------------------------------------
    // stub
    // Used by -stub-run mode for lightweight CI validation.
    // Creates empty placeholder report files so Nextflow can verify
    // channel wiring without executing samtools, bcftools, or Python.
    // -----------------------------------------------------------------------
    stub:
    """
    touch ${sample}_qc_report.txt
    touch ${sample}_qc_report.html
    """
}
